/* Copyright 2010-2011 Ilkka Halila
             2020-2022 Nikolay Shaplov (aka dhyan.nataraj)
This file is part of Goblin Camp.

Goblin Camp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Goblin Camp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with Goblin Camp. If not, see <http://www.gnu.org/licenses/>.*/
#include "stdafx.hpp"

#include "Version.hpp"

/**
	Global variables container.
*/
namespace Globals {
	/**
		\var gameVersion
			Current game version. It should be automatically generated by the build system.
	*/
#if !defined(GCAMP_VERSION)
#define GCAMP_VERSION "[Unkown version]"
#endif

#if ! GCAMP_VERSION_IS_RELEASE
#define GCAMP_FULL_VERSION "v" GCAMP_VERSION " (dev)"
#else
#define GCAMP_FULL_VERSION "v" GCAMP_VERSION
#endif
	const char *gameVersion = "Goblin Camp " GCAMP_FULL_VERSION;
}
